debug: true
pose_topic: pose
enable_tf: false
robot_as_parent: true
camera_tf_name: camera_optical_frame
map_tf_name: map
base_tf_name: base_link
camera_matrix: [1130.458671, 0.000000, 545.323771, 0.000000, 1154.159372, 262.356965, 0.000000, 0.000000, 1.000000]
camera_distortion: [0.053037, 0.116553, 0.000778, 0.004628, 0.000000]
image_topic: arm/camera1/image_raw
markers_dictionary: 11
markers_length: [50] # length in mm.
markers_200: [0, 1, 2, 3, 4, 5, 6, 12, 13, 14, 15, 16, 17, 18, 207] # Markers id with length 0.
markers_sufix: id_
static_camera_transform: false
static_marker: true
static_markers_id: [2, 4, 6]
static_variance: false
variance_matrix: [0.01, 0, 0, 0, 0, 0, 
                  0, 0.01, 0, 0, 0, 0,
                  0, 0, 0.01, 0, 0, 0,
                  0, 0, 0, 0.01, 0, 0,
                  0, 0, 0, 0, 0.01, 0,
                  0, 0, 0, 0, 0, 0.01]