debug: true
pose_topic: pose
enable_tf: false
robot_as_parent: true
camera_tf_name: camera_optical_frame
map_tf_name: map
base_tf_name: base_link
camera_matrix: [554.254691191187, 0.0, 0.0, 0.0, 554.254691191187, 0.0, 0.0, 0.0, 1.0]
camera_distortion: [0.0, 0.0, 0.0, 0.0, 0.0]
image_topic: /cv_camera/image_raw
markers_dictionary: 11
markers_length: [200] # length in mm.
markers_200: [0, 1, 2, 3, 4, 5, 6, 12, 13, 14, 15, 16, 17, 18, 207] # Markers id with length 0.
markers_sufix: id_
static_camera_transform: false
static_marker: true
static_markers_id: [2, 4, 6]
static_variance: false
variance_matrix: [0.01, 0, 0, 0, 0, 0, 
                  0, 0.01, 0, 0, 0, 0,
                  0, 0, 0.01, 0, 0, 0,
                  0, 0, 0, 0.01, 0, 0,
                  0, 0, 0, 0, 0.01, 0,
                  0, 0, 0, 0, 0, 0.01]